language: php

php:
  - 7.0
  - 7.1
  - nightly

cache:
  directories:
    - $HOME/.composer/cache

env:
  matrix:
    - LARAVEL_VERSION="5.1.*"
    - LARAVEL_VERSION="5.2.*"
    - LARAVEL_VERSION="5.3.*"
    - LARAVEL_VERSION="5.4.*"
    - LARAVEL_VERSION="dev-master"

matrix:
  allow_failures:
    - env: LARAVEL_VERSION="dev-master"
  fast_finish: true

before_install:
  - travis_retry composer self-update
  - composer require laravel/framework=${LARAVEL_VERSION} --no-update

install:
  - travis_retry composer update --no-interaction --prefer-dist

script:
  - vendor/bin/phpunit

branches:
  only:
    - master
    - develop
    - feature/testing/refactor-tests

notifications:
  email:
    on_failure: change
    on_success: never
