language: php

php:
  - 7.0

cache:
  directories:
    - $HOME/.composer/cache

env:
  matrix:
    - LARAVEL_VERSION="5.1.*"
    - LARAVEL_VERSION="5.4.*"

before_install:
  - travis_retry composer self-update
  - composer require laravel/framework=${LARAVEL_VERSION} --no-update

install:
  - travis_retry composer update --no-interaction --prefer-dist

script:
  - vendor/bin/phpunit

branches:
  only:
    - master
    - develop
    - feature/testing/refactor-tests

notifications:
  email:
    on_failure: change
    on_success: never
