language: php

php:
  - 7.0

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
- LARAVEL_VERSION="5.4.*" COMPOSER_FLAGS="--prefer-lowest"
- LARAVEL_VERSION="5.4.*" COMPOSER_FLAGS=""

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer update ${COMPOSER_FLAGS} --dev --no-interaction --prefer-dist
  - travis_retry composer require laravel-framework:${LARAVEL_VERSION} --no-update

script:
  - vendor/bin/phpunit

branches:
  only:
    - master
    - develop
    - feature/testing/refactor-tests

notifications:
    email:
        on_failure: change
        on_success: never
