language: php

php:
  - 5.6
  - 7.0
  - 7.1
  
sudo: false

cache:
  directories:
    - $HOME/.composer/cache
    
env:
  matrix:
    - COMPOSER_FLAGS="--prefer-lowest"
    - COMPOSER_FLAGS=""

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist
  
notifications:
    email:
        on_failure: change
        on_success: never